Version 2.0

---
Children:
- Children:
  - Children: []
    Properties:
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: []
    Base: Subsystem
    Name: DriveTrain
  - Children:
    - Children: []
      Properties:
        Type: !!robotbuilder.data.properties.ChoicesProperty
          choices: &id001 [Victor, Jaguar, Talon, VictorSP, TalonSRX, Spark, SD540]
          default: Talon
          name: Type
          validators: null
          value: Victor
        Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
          choices: &id002 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
            '11', '12', '13', '14', '15', '16', '17', '18', '19']
          default: '0'
          name: Output Channel (PWM)
          validators: &id003 [PWMOutput]
          value: '0'
      Base: Speed Controller
      Name: conveyorMotor
    Properties:
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: &id004 []
    Base: Subsystem
    Name: Launcher
  - Children:
    - Children: []
      Properties:
        Type: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id001
          default: Talon
          name: Type
          validators: null
          value: Victor
        Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id002
          default: '0'
          name: Output Channel (PWM)
          validators: *id003
          value: '1'
      Base: Speed Controller
      Name: collectorMotor
    Properties:
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: *id004
    Base: Subsystem
    Name: Collector
  - Children:
    - Children: []
      Properties:
        Type: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id001
          default: Talon
          name: Type
          validators: null
          value: Victor
        Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id002
          default: '0'
          name: Output Channel (PWM)
          validators: *id003
          value: '3'
      Base: Speed Controller
      Name: climber2
    - Children: []
      Properties:
        Type: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id001
          default: Talon
          name: Type
          validators: null
          value: Victor
        Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id002
          default: '0'
          name: Output Channel (PWM)
          validators: *id003
          value: '2'
      Base: Speed Controller
      Name: climber1
    Properties:
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value:
        - !!robotbuilder.data.properties.ValuedParameterDescriptor {name: speed, type: double,
          value: '0'}
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: Climb}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: *id004
    Base: Subsystem
    Name: Climber
  - Children:
    - Children: []
      Properties:
        Output Channel (Relay): !!robotbuilder.data.properties.ChoicesProperty
          choices: &id005 ['0', '1', '2', '3']
          default: '0'
          name: Output Channel (Relay)
          validators: &id006 [RelayOutput]
          value: '0'
      Base: Spike
      Name: spike1
    - Children: []
      Properties:
        Output Channel (Relay): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id005
          default: '0'
          name: Output Channel (Relay)
          validators: *id006
          value: '1'
      Base: Spike
      Name: spike2
    Properties:
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: &id007 []
    Base: Subsystem
    Name: LEDs
  - Children: []
    Properties:
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: *id007
    Base: Subsystem
    Name: Vision
  - Children:
    - Children: []
      Properties:
        Sensitivity: !!robotbuilder.data.properties.DoubleProperty {default: 0.007,
          name: Sensitivity, validators: null, value: 0.007}
        Input Channel (Analog): !!robotbuilder.data.properties.ChoicesProperty
          choices: ['0', '1']
          default: '0'
          name: Input Channel (Analog)
          validators: [AnalogInput]
          value: '0'
      Base: AnalogGyro
      Name: gyro
    - Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: &id008 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
            '11', '12', '13', '14', '15', '16', '17', '18', '19', '20']
          default: '2'
          name: CAN ID
          validators: &id009 [CANID]
          value: '1'
      Base: CAN Talon
      Name: leftMotor1
    - Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id008
          default: '2'
          name: CAN ID
          validators: *id009
          value: '2'
      Base: CAN Talon
      Name: leftMotor2
    - Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id008
          default: '2'
          name: CAN ID
          validators: *id009
          value: '3'
      Base: CAN Talon
      Name: leftMotor3
    - Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id008
          default: '2'
          name: CAN ID
          validators: *id009
          value: '4'
      Base: CAN Talon
      Name: rightMotor1
    - Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id008
          default: '2'
          name: CAN ID
          validators: *id009
          value: '5'
      Base: CAN Talon
      Name: rightMotor2
    - Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id008
          default: '2'
          name: CAN ID
          validators: *id009
          value: '6'
      Base: CAN Talon
      Name: rightMotor3
    - Children: []
      Properties:
        Input Channel (Analog): !!robotbuilder.data.properties.ChoicesProperty
          choices: ['0', '1', '2', '3', '4', '5', '6', '7']
          default: '0'
          name: Input Channel (Analog)
          validators: [AnalogInput]
          value: '1'
      Base: Analog Input
      Name: prox1
    Properties:
      Limit Output: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Limit Output, validators: null, value: false}
      D: !!robotbuilder.data.properties.DoubleProperty {default: 0, name: D, validators: null,
        value: 0.0}
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Continuous: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Continuous, validators: null, value: false}
      F: !!robotbuilder.data.properties.DoubleProperty {default: 0, name: F, validators: null,
        value: 0.0}
      Tolerance: !!robotbuilder.data.properties.DoubleProperty {default: 0.2, name: Tolerance,
        validators: null, value: 0.2}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: []
      I: !!robotbuilder.data.properties.DoubleProperty {default: 0, name: I, validators: null,
        value: 0.0}
      Minimum Input: !!robotbuilder.data.properties.DoubleProperty {default: 0, name: Minimum Input,
        validators: null, value: 0.0}
      Limit Input: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Limit Input, validators: null, value: false}
      Minimum Output: !!robotbuilder.data.properties.DoubleProperty {default: -1,
        name: Minimum Output, validators: null, value: -1.0}
      P: !!robotbuilder.data.properties.DoubleProperty {default: 1, name: P, validators: null,
        value: 1.0}
      Input: !!robotbuilder.data.properties.ChildSelectionProperty
        default: 0
        name: Input
        type: PIDSource
        validators: [ChildDropdownSelected]
        value: PIDDrive gyro
      Maximum Output: !!robotbuilder.data.properties.DoubleProperty {default: 1, name: Maximum Output,
        validators: null, value: 1.0}
      Output: !!robotbuilder.data.properties.ChildSelectionProperty
        default: 0
        name: Output
        type: PIDOutput
        validators: [ChildDropdownSelected]
        value: PIDDrive leftMotor1
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: Drive}
      Maximum Input: !!robotbuilder.data.properties.DoubleProperty {default: 5, name: Maximum Input,
        validators: null, value: 5.0}
    Base: PID Subsystem
    Name: PIDDrive
  Properties: {}
  Base: Subsystems
  Name: Subsystems
- Children:
  - Children: []
    Properties:
      Number: !!robotbuilder.data.properties.ChoicesProperty
        choices: &id010 ['0', '1', '2', '3', '4', '5']
        default: 1
        name: Number
        validators: &id011 [Joystick]
        value: '0'
    Base: Joystick
    Name: driverLeftStick
  - Children: []
    Properties:
      Number: !!robotbuilder.data.properties.ChoicesProperty
        choices: *id010
        default: 1
        name: Number
        validators: *id011
        value: '1'
    Base: Joystick
    Name: driverRightStick
  - Children: []
    Properties:
      Number: !!robotbuilder.data.properties.ChoicesProperty
        choices: *id010
        default: 1
        name: Number
        validators: *id011
        value: '2'
    Base: Joystick
    Name: operatorStick
  Properties: {}
  Base: OI
  Name: Operator Interface
- Children:
  - Children: []
    Properties:
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: PIDDrive}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: []
        name: Parameter presets
        validators: null
        value: []
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
    Base: Command
    Name: Drive
  - Children: []
    Properties:
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Launcher}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: []
        name: Parameter presets
        validators: null
        value: []
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
    Base: Command
    Name: BasicLaunchFuel
  - Children: []
    Properties:
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Collector}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: []
        name: Parameter presets
        validators: null
        value: []
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
    Base: Command
    Name: CollectFuel
  - Children: []
    Properties:
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value:
        - !!robotbuilder.data.properties.ParameterDescriptor {name: speed, type: double}
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Climber}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: []
        name: Parameter presets
        validators: null
        value: []
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
    Base: Command
    Name: Climb
  - Children: []
    Properties:
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: PIDDrive}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: []
        name: Parameter presets
        validators: null
        value: []
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: true}
    Base: Command
    Name: DriveToGearPeg
  - Children: []
    Properties:
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: PIDDrive}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: []
        name: Parameter presets
        validators: null
        value: []
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: true}
    Base: Command
    Name: PIDTurn
  - Children: []
    Properties:
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: PIDDrive}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: &id012 []
        name: Parameter presets
        validators: null
        value: *id012
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: true}
    Base: Command
    Name: moveTo
  Properties: {}
  Base: Commands
  Name: Commands
Properties:
  Eclipse Workspace: !!robotbuilder.data.properties.FileProperty {default: 'C:\Users\vijay\workspace',
    extension: null, folder: true, name: Eclipse Workspace, validators: null, value: 'C:\FRCWorkspace'}
  Export Commands: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Commands, validators: null, value: true}
  Autonomous command parameters: !!robotbuilder.data.properties.ParametersProperty
    default: []
    name: Autonomous command parameters
    validators: null
    value: []
  Java Package: !!robotbuilder.data.properties.StringProperty {default: org.usfirst.frc0000,
    name: Java Package, validators: null, value: org.usfirst.frc1073}
  Use Default Java Package: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Use Default Java Package, validators: null, value: true}
  Team Number: !!robotbuilder.data.properties.IntegerProperty {default: 0, name: Team Number,
    validators: null, value: 1073}
  Export Subsystems: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Subsystems, validators: null, value: true}
  Simulation World File: !!robotbuilder.data.properties.StringProperty {default: /usr/share/frcsim/worlds/GearsBotDemo.world,
    name: Simulation World File, validators: null, value: /usr/share/frcsim/worlds/GearsBotDemo.world}
  Wiring file location: !!robotbuilder.data.properties.FileProperty {default: 'C:\Users\vijay\',
    extension: null, folder: true, name: Wiring file location, validators: null, value: 'C:\FRCWorkspace\robot17'}
  Autonomous Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
    name: Autonomous Command, type: Command, validators: null, value: None}
Base: Robot
Name: robot17
