// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.robot17.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc1073.robot17.RobotMap;
import org.usfirst.frc1073.robot17.Robot;

/**
 *
 */
public class AutoTurnWithPID extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutoTurnWithPID() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.pidDrive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    double error;
    double angle;
    double p, i, d;


    // Called just before this Command runs the first time
    protected void initialize() {    	
    	RobotMap.headingGyro.reset();
    	Robot.pidDrive.getPIDController().reset();
    	Robot.pidDrive.setSetpoint(-50); // 50 degrees for now
    	SmartDashboard.getNumber("P", p);
    	SmartDashboard.getNumber("I", i);
    	SmartDashboard.getNumber("D", d);
    	Robot.pidDrive.getPIDController().setPID(p, i, d);
    	Robot.pidDrive.enable();
    	Robot.pidDrive.setAbsoluteTolerance(10);	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	error = Robot.pidDrive.getPIDController().getError();
    	SmartDashboard.putNumber("Error",error );
    	angle = RobotMap.headingGyro.getAngle();
    	SmartDashboard.putNumber("Angle",angle );
    	RobotMap.driveTrainleftMotor1.set(-0.3);
    	RobotMap.driveTrainrightMotor1.set(0.3);
    }

    protected boolean isFinished() {
    	if(Math.abs(Robot.pidDrive.getPIDController().getError() ) < 50)
    		return true;
    	else
    		return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.pidDrive.disable();
    	
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
