// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.robot17.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc1073.robot17.Logger;
import org.usfirst.frc1073.robot17.Robot;
import org.usfirst.frc1073.robot17.RobotMap;

/**
 *
 */
public class DistanceToWall extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DistanceToWall() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
double backProximity = 0;   
double frontProximity;
double voltage;
double reciprocal;
int i;
double[] proxArray;
double averageVoltage = 0;
    // Called just before this Command runs the first time
    protected void initialize() {
    	i = 0;
    	SmartDashboard.putNumber("BackDistance", 0);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	voltage =  RobotMap.driveTrainProximitySensorBack.getVoltage();
    	reciprocal = 0.00126675995064 * Math.pow(voltage, 4) + -0.00823083172345 * Math.pow(voltage, 3) + 0.02292474310105 * Math.pow(voltage, 2) + 0.01747977657017 * voltage + 0.00285999025946;
    	proxArray[i] = voltage;
    	i = i + 1;
    	if (i > 9){
    		i = 0;
    	}
    	for (int x=0; x < 10; x++){
    		averageVoltage = averageVoltage + proxArray[x];
    	}
    	averageVoltage = averageVoltage / 10;
    	reciprocal = 0.00126675995064 * Math.pow(averageVoltage, 4) + -0.00823083172345 * Math.pow(averageVoltage, 3) + 0.02292474310105 * Math.pow(averageVoltage, 2) + 0.01747977657017 * averageVoltage + 0.00285999025946;
    	backProximity = 1 / reciprocal;
    	backProximity = backProximity / 2.54;
    	
    	SmartDashboard.putNumber("BackDistance", backProximity);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {   	
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
