// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.robot17.commands;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc1073.robot17.Robot;
import org.usfirst.frc1073.robot17.RobotMap;
import org.usfirst.frc1073.robot17.Logger;
import org.usfirst.frc1073.robot17.OI;
import edu.wpi.first.wpilibj.networktables.NetworkTable;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.Preferences;

/**
 *
 */
public class LidarTest0 extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    
	//Set up for the NetworkTable variables the Raspberry Pi sends
	NetworkTable lidarSendTable;
    double LidarDegrees;
    double LidarDistance;
    
    
    //Variable for button used in isFinished
    boolean isPressed = false;
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public LidarTest0() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
    	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        
        //Sets the correct Network Table to pull from the Pixy
        lidarSendTable = NetworkTable.getTable("LidarSendTable");
    }

    protected void initialize() {
    	
    	
    	SmartDashboard.putString("lidar info", "starting");

    	Robot.bling.sendAutoDone();
    }

    protected void execute() {
    	
    	//These are the variables that get manipulated in the code

        double mmToIn = 2.54;
       
        //These are the variables for speed - start slow
		
		//These are what the Pixy send us
		LidarDistance =  lidarSendTable.getNumber("LidarDistance", 0);
        LidarDegrees =  lidarSendTable.getNumber("LidarDegrees", 0);
        
        Logger.setLog(Double.toString(LidarDistance));
        Logger.setLog(Double.toString(LidarDegrees));
		
		//This code modifies the speed based on how close you are to the peg
        SmartDashboard.putNumber("Lidar Distance" , LidarDistance);
        SmartDashboard.putNumber("Lidar Degrees" , LidarDegrees);
        SmartDashboard.putNumber("Lidar To Inches", LidarDistance/mmToIn);
       if ((LidarDistance / mmToIn) > 36 ) {
    	   SmartDashboard.putString("lidar info", "closest object = >3ft");
    	   Robot.driveTrain.basicDrive(.5, .5);
       }
       else if ((LidarDistance / mmToIn) > 24 && (LidarDistance / mmToIn) < 36 ) {
    	   SmartDashboard.putString("lidar info", "closest object = <3ft and >2ft");
    	   Robot.driveTrain.basicDrive(.25, .25);
       
       }
       else if ((LidarDistance / mmToIn) > 12 && (LidarDistance / mmToIn) < 24 ) {
    	   SmartDashboard.putString("lidar info", "closest object = <2ft and >1ft");
    	   Robot.driveTrain.basicDrive(.15, .15);
       }
       else if ((LidarDistance / mmToIn) > 6 && (LidarDistance / mmToIn) <12) {
    	   SmartDashboard.putString("lidar info", "closest object = <1ft and >.5ft");
    	   Robot.driveTrain.basicDrive(.1, .1);
       }
       else if ((LidarDistance / mmToIn) < 6) {
    	   SmartDashboard.putString("lidar info", "STOP! :)");
    	   Robot.driveTrain.basicDrive(0, 0);
       }
       else {
    	   SmartDashboard.putString("lidar info", "not moving in ELSE");
    	   
    	   Robot.driveTrain.basicDrive(.5,.5);
    	   
       }
       }
    
    protected boolean isFinished() {
   	
    	
    	
    	//Checks the cancel button for its state
    	isPressed = Robot.oi.cancelAny.get();
    	if (true){
    SmartDashboard.putString("hello_world", "isFinished");
    		return false;
    	}	
    	else {
    		return true;
    	}
    }
    
    protected void end() {
    	//Stops motors and sets bling
    	Robot.driveTrain.basicDrive(0, 0);
    	Robot.bling.sendRemoveGear();
    }

    protected void interrupted() {
    	//Stops motors and sets bling
    	Robot.driveTrain.basicDrive(0, 0);
    	SmartDashboard.putString("lidar info", "Interrupted");
    	Robot.bling.sendRemoveGear();
    }
}
