// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.robot17;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController launcherconveyorMotor;
    public static SpeedController collectorcollectorMotor;
    public static SpeedController climberclimber2;
    public static SpeedController climberclimber1;
    public static Relay lEDsspike1;
    public static Relay lEDsspike2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        launcherconveyorMotor = new Victor(0);
        LiveWindow.addActuator("Launcher", "conveyorMotor", (Victor) launcherconveyorMotor);
        
        collectorcollectorMotor = new Victor(1);
        LiveWindow.addActuator("Collector", "collectorMotor", (Victor) collectorcollectorMotor);
        
        climberclimber2 = new Victor(3);
        LiveWindow.addActuator("Climber", "climber2", (Victor) climberclimber2);
        
        climberclimber1 = new Victor(2);
        LiveWindow.addActuator("Climber", "climber1", (Victor) climberclimber1);
        
        lEDsspike1 = new Relay(0);
        LiveWindow.addActuator("LEDs", "spike1", lEDsspike1);
        
        lEDsspike2 = new Relay(1);
        LiveWindow.addActuator("LEDs", "spike2", lEDsspike2);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
